defaults:
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: colorlog
  - _self_

hydra:
  run:
    dir: ./outputs/${dataset.name}/${dataset.choice}/${llm_model.model_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}-${generate_job_id:}

  job_logging:
    handlers:
      file:
        filename: ${hydra.run.dir}/log.log

concurrency:
  mode: linear # linear, parallel
  max_workers: 4 # if mode is parallel

seed: 42

debug:
  enable: False
  max_tasks: 2

llm_model:
  model_id: Qwen/QwQ-32B
  model_name: QwQ-32B
  provider: localhost
  localhost:
    api_base: "http://localhost:8000/v1"
    api_key: "token-abc123"


dataset:
  name: strongreject
  choice: small
  small_dataset: ./datasets/strongreject/strongreject_small_dataset.csv
  full_dataset: ./datasets/strongreject/strongreject_dataset.csv
  evaluator:
    - strongreject_rubric_vllm
#    - strongreject_rubric # openAI
#    - strongreject_finetuned # HF FT model

evaluate: true

text_inspector_max_limit: 100000

browser_config:
  viewport_size: 5120 # 1024 * 5
  downloads_folder: downloads_folder
  request_kwargs:
    headers:
      user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
    timeout: 300
  serpapi_key: SERPAPI_API_KEY

search_agent:
  max_steps: 20
  verbosity_level: 2
  planning_interval: 4
  name: search_agent
  description: search_agent_description
  provide_run_summary: True

manager_agent:
  max_steps: 12
  verbosity_level: 2
  planning_interval: 4
  name: manager_agent

