version: 1
formatters:
  simple:
    format: '[%(levelname)s:%(asctime)s:%(name)s:%(filename)s:%(lineno)d]: %(message)s'
    datefmt: "%m/%d/%Y %H:%M:%S"
  colorlog:
    '()': 'colorlog.ColoredFormatter'
    format: '[%(cyan)s%(asctime)s%(reset)s][%(blue)s%(name)s%(reset)s][%(log_color)s%(levelname)s%(reset)s][%(filename)s:%(lineno)d] - %(message)s'
    log_colors:
      DEBUG: purple
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: red
handlers:
  console:
    class: logging.StreamHandler
    formatter: colorlog
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: log.log
root:
  handlers: [console, file]
disable_existing_loggers: false